#version 450

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer A {
    float a[];
} in_a;

layout(std430, binding = 1) readonly buffer B {
    float b[];
} in_b;

layout(std430, binding = 2) buffer OutputY {
    float y[];
} out_y;

layout(push_constant) uniform Push {
    uint n;
} pc;

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= pc.n) {
        return;
    }
    out_y.y[i] = in_a.a[i] + in_b.b[i];
}
