#version 450

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) buffer Latent {
    float latent[];
} inout_latent;

layout(std430, binding = 1) readonly buffer Velocity {
    float velocity[];
} in_velocity;

layout(push_constant) uniform Push {
    uint n;
    float dsigma;
} pc;

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= pc.n) {
        return;
    }
    inout_latent.latent[i] += pc.dsigma * in_velocity.velocity[i];
}
